kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mediawiki-data
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
