apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mariadb.selectorLabels" . | nindent 4 }}
